CREATE SCHEMA [frontful]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [frontful].[content](
	[group] [varchar](50) NOT NULL,
	[key] [varchar](150) NOT NULL,
	[value] [nvarchar](max) NULL,
 CONSTRAINT [PK_content] PRIMARY KEY CLUSTERED 
(
	[group] ASC,
	[key] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
