module.exports = {
  packages: [
    'babel-preset-frontful',
    'eslint-config-frontful',
    'frontful-cms',
    'frontful-common',
    'frontful-components',
    'frontful-config',
    'frontful-dao',
    'frontful-environment',
    'frontful-field',
    'frontful-model',
    'frontful-resolver',
    'frontful-router',
    'frontful-store-sql',
    'frontful-style',
    'frontful-tools',
    'frontful-utils',
  ],
  alias: {},
}
